Develop
EkBratchik/Java_Lab3 pull request #1
Opened 2020-09-23 18:45 UTC by EkBratchik

2020-09-23 19:18 UTC, VeronikaYastr requested changes

2020-09-23 19:18 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +        public static void main(String []args){
Логика правильная, но
- названия почему с подчеркиванием?🤔 CamelCase же
- Зачем нужен какой-то тест_текст?))
- Тестов нет

2020-09-24 06:16 UTC, EkBratchik commented on src/main/java/com/bsu/Main.java
> +        public static void main(String []args){
Я могу сразу сюда скинуть тест? Или надо перезаливать?

2020-09-24 11:34 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +        public static void main(String []args){
Можешь в эту же ветку перезалить файлы. Новый пул реквест не нужно создавать

2020-09-24 11:35 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +            Scanner k = new Scanner(System.in);
А зачем тебе два сканера?
И у тебя получается оба не закрыты и оба не в try-catch. В общем что-то странное получилось

2020-09-24 11:36 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +        public static String remove_first_words(String text, int count){
Все еще с подчеркиванием осталось название

2020-09-25 07:13 UTC, EkBratchik commented on src/main/java/com/bsu/Main.java
> +            Scanner k = new Scanner(System.in);
Исправила

2020-09-25 20:11 UTC, VeronikaYastr requested changes

2020-09-25 20:11 UTC, VeronikaYastr commented on src/test/java/com/bsu/Testing.java
> +    public void testMain() {
какой-то странный тест. тут без ассертов никаких проверок нет)
Лучше убрать весь вывод в консоль и просто сделать assertEquals(text, formattedText)

2020-09-25 20:11 UTC, VeronikaYastr commented on src/main/java/com/bsu/Main.java
> +                String phrase1 = sc.nextLine();
Не очень название phrase1, лучше более осмысленное)

2020-09-30 20:12 UTC, VeronikaYastr commented
👍

2020-10-01 07:01 UTC, merged